---
- name: Install the latest version of Apache2
  hosts: all
  become: true
  tasks:
    - name: Install apache2 package
      apt:
        name: apache2
        state: latest
        update_cache: yes
        

